name: Upstream Packages Version Check
on:
  push:
    branches: main
    paths:
      - ".github/workflows/sync.yml"
      - "config.json"

  schedule:
    - cron: 12 */6 * * *

jobs:
  buildpkg:
    name: Fetch feeds
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.PUSH_TOKEN }}

      - name: Fetch feeds
        uses: Purple-wind-bell/feed-builder@main

      - name: Commit
        run: |
          git config user.name "bot"
          git config user.email "bot@github.com"
          git add .
          if [ -z "$(git status --porcelain)" ]; then
            echo "No changes to commit"
            exit 0
          fi
          git commit -m "Sync $(TZ='Asia/Shanghai' date +@%Y%m%d-%H%M%S)"
          git push -f --quiet "https://x-access-token:${{ secrets.PUSH_TOKEN }}@github.com/$GITHUB_REPOSITORY" HEAD:main
